### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by huzaifa1712** [usdevs/usc-website-hackathon-frontend#6]
### Flow 
User will enter Telegram handle and then the OTP
Login page will interact with Telegram API
Telegram API will return JWT
Send JWT as BearerToken when talking to backend API

### Tasks 
- [x] Add UI components to the header to enable users to sign in --> we can do either a popup or redirect to a new login page
- [x] Add an Auth wrapper to the bookings page to verify if user is signed in before booking, and to redirect to login page before making booking
- [x] Create the interactions with Telegram API and the backend API
- [x] Form validation - read the error message from the backend and use it to validate the frontend
